const { mongoose } = require('../../Shared/config');
const { connectDB } = require('../../Shared/config');

const asyncHandler = require("express-async-handler")

// Create controller quote function with debugging
const quote = asyncHandler(async(req, res) => {
    console.log('👤 User from middleware:', req.user ? `ID: ${req.user._id}` : 'MISSING');
    console.log('📊 DB Connection State:', mongoose.connection.readyState);
    
    const {data, vat, subtotal, totalSum} = req.body
    
    try { 
        await connectDB(); // Ensure DB is connected before proceeding
        const QuoteModel = require("../models/quoteModel.js")
        
        console.log('📝 Creating new quote...');
        
        // Create new quote (quoteNumber will be auto-generated by the pre-save hook)
        const newQuote = new QuoteModel({
            data, // Now an array of input objects
            totalSum,
            subtotal,
            vat,
            user: req.user._id // Ensure user ID is included
        });

        console.log('💾 Before save - quoteNumber:', newQuote.quoteNumber);

        // Save the quote (this will trigger the pre-save hook to generate quoteNumber)
        const savedQuote = await newQuote.save();
        
        console.log('✅ After save - quoteNumber:', savedQuote.quoteNumber);
        console.log('📄 Full saved quote:', JSON.stringify(savedQuote, null, 2));
        
        res.status(201).json(savedQuote);
        
    } catch (error) {
        console.error('❌ Error creating quote:', error);
        res.status(400).json({ message: error.message });
    }
})

// Get current most recent quote
const getQuote = asyncHandler(async (req, res) => {
    try {
        await connectDB(); // Ensure DB is connected before proceeding
        const QuoteModel = require("../models/quoteModel.js")
        
        const recentQuote = await QuoteModel.findOne({ user: req.user._id }).sort({ createdAt: -1 });

        if (!recentQuote) {
            return res.status(404).json({ message: "No quotes found" });
        }

        res.status(200).json(recentQuote);
        
    } catch (error) {
        console.error("Error fetching the latest quote:", error);
        res.status(500).json({ message: "Error fetching the latest quote" });
    }
});

// Get all quotes
const getAllQuotes = asyncHandler(async (req, res) => {
    try {
        await connectDB(); // Ensure DB is connected before proceeding
        const QuoteModel = require("../models/quoteModel.js")
        
        const quotes = await QuoteModel.find({ user: req.user._id }).sort({ createdAt: -1 }); // Fetch all quotes sorted by newest first

        // Always return 200 with array (empty if none)
        res.status(200).json(quotes); // Changed: No 404, just empty array if !quotes.length
        
    } catch (error) {
        console.error("Error fetching quotes:", error);
        res.status(500).json({ message: "Error fetching quotes" });
    }
});

const deleteQuote = asyncHandler(async (req, res) => {
    const { id } = req.params;
  
    try {
      console.log('🗑️ Delete request started');
      console.log('📋 Quote ID:', id); // Fixed: "Quote ID"
      console.log('👤 User from middleware:', req.user ? `ID: ${req.user._id}` : 'MISSING');
  
      await connectDB(); // Ensure database connection
      const Quote = require("../models/quoteModel.js");
      
      // Find the quote first to check if it exists and belongs to the user
      const quoteToDelete = await Quote.findById(id);
      
      if (!quoteToDelete) {
        console.log('❌ Quote not found');
        return res.status(404).json({ message: "Quote not found" });
      }
  
      console.log('📋 Found quote user:', quoteToDelete.user);
      console.log('🔐 Current user:', req.user._id);
  
      // Check if the quote belongs to the current user - FIXED COMPARISON
      if (quoteToDelete.user && req.user && quoteToDelete.user.toString() !== req.user._id.toString()) {
        console.log('🚫 Authorization failed - user mismatch');
        return res.status(403).json({ message: "Not authorized to delete this quote" }); // Fixed: "quote"
      }
  
      // Delete the quote
      await Quote.findByIdAndDelete(id);
      
      console.log('✅ Quote deleted successfully'); // Fixed: "Quote"
      res.status(200).json({ 
        message: "Quote deleted successfully", // Fixed: "Quote"
        deletedQuoteId: id 
      });
    } catch (error) {
      console.error("❌ Error deleting quote:", error); // Fixed: "quote"
      res.status(500).json({ message: "Error deleting quote", error: error.message }); // Fixed: "quote"
    }
  });

module.exports = {quote,deleteQuote, getAllQuotes, getQuote}